version: '3'

services:
  active-speaker-detection:
    image: talk:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8080:8080"
    restart: unless-stopped
