models:
    min-workers: 1
    max-workers: 1
    batch-size: 1
    max-batch-delay: 100
    retry-attempts: 3
    timeout-ms: 30000

    s3fd:
      url: s3fd.mar
    # lightcnn:
    #   url: lightcnn.mar

dag:
  pre_processing: [s3fd]
  #, lightcnn]
  # mtcnn: [lightcnn]