models:
    min-workers: 1
    max-workers: 1
    batch-size: 1
    max-batch-delay: 100
    retry-attempts: 3
    timeout-ms: 30000

    s3fd:
      url: s3fd.mar
    talk:
      url: talk.mar
    
dag:
  pre_processing: [s3fd]
  s3fd: [talk]